# _config.yml
title: Lunabotics Documentation
description: Technical docs for the Lunabotics project.
theme: jekyll-theme-cayman

# The following options are optional but nice to have:
markdown: kramdown

# GitHub Pages plugins (all safe & supported)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Optional: default layout for your Markdown files
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"